53 review pagination functionality
DominykasSueris/watch_land pull request #60
Opened 2023-05-11 19:42 UTC by DominykasSueris

Aws Logs stream padination functionality fixed, also outline border removed and adjusted to center.

Please approve changes and merge to main @augustinasrce @Konstantin-Bozhkov

2023-05-11 21:04 UTC, DominykasSueris commented
Pagination merge conflict fixed.

2023-05-12 11:58 UTC, Konstantin-Bozhkov commented
Please merge branch "main"

2023-05-12 12:03 UTC, Konstantin-Bozhkov requested changes

2023-05-12 12:03 UTC, Konstantin-Bozhkov commented on src/utils/arrays.ts
> +export const PerPage = 6;
Lets increase this to 50

2023-05-12 12:04 UTC, Konstantin-Bozhkov commented on src/utils/arrays.ts
> +export const PerPage = 6;
@DominykasSueris

2023-05-12 12:06 UTC, Konstantin-Bozhkov approved these changes

2023-05-12 12:06 UTC, merged